/// @description 
if(instance_exists(obj_player))
{
	if(obj_player.current_mission!=noone)
	{
		if(obj_player.current_mission._type!=TYPE.ESCORT)
		{
			instance_destroy(id);
		}
	}
	if(target_in_range(obj_station,_range))
	{
		move_towards_point(obj_station.x,obj_station.y,8);
		if(obj_player.current_mission!=noone)
		{
			obj_player.current_mission.complete_mission();
			obj_player.allies_saved++;
		}
	}
	if(place_meeting(x,y,obj_station))
	{
		instance_destroy(id);
	}
}